### ISSUE TITLE
Message: Not Found

### ISSUE THREAD

**Issue by lordicecream** [sap1ens/heimdall#5]
I have tried deploying this as per the documentation, how when the UI loads, I am seeing error : "Cloudn't load data : AxiosError: Request failed with status code 500"
when I check the pod logs seeing : "HTTP Request to /jobs failed, Failure executing GET at : https://<kube-api-server>/<path to flink deployment>.  Message: Not found "

Could you suggest how to go about rectifying this?

**Comment by sap1ens** [comment]
Hmm, this is really weird, I haven't seen an issue like this before. It's probably related to a Kubernetes client. How do you access it? Is it running locally via something like a Minikube? Or is it a remote cluster?

**Comment by lordicecream** [comment]
It's a remote cluster, I am seeing flink job names in the pod as environment variables....that led me to believe that Heimdall is successfully fetching the deployments, but is still running into some other issues clearly.
Is there some Flink/Flink-operator compatibility matrix to consider?
Any pointers to consider how to troubleshoot further.

**Comment by sap1ens** [comment]
I'd enable DEBUG level logging to understand what's going on better. 

Did you enable the right permissions using something like [this](https://github.com/sap1ens/heimdall/blob/main/tools/k8s-operator/service-account.yaml)?

**Comment by lordicecream** [comment]
Yes, validated the service account access multiple times, even using the kubectl can-i command...
How can I enable DEBUG level Logging?

**Comment by lordicecream** [comment]
Resolved

**Comment by lordicecream** [comment]
Resolvee
